version: '3'

services:
  mysql:
    image: mysql
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/:ro
